name: Build J2V8

on: [push]

jobs:
  build_j2v8_linux_x86_64:
    name: Create J2V8 Linux jar archive file
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build V8 and J2V8 for Linux
      run: |
        python2 build.py -t linux -a x64 --docker v8 j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java j2v8test

    - name: Archive J2V8 Linux x86_64 jar
      uses: actions/upload-artifact@v1.0.0
      with:
        name: j2v8-linux-x86_64
        path: build.out/j2v8_linux_x86_64-6.2.0.jar

  build_j2v8_android:
    name: Create J2V8 Android aar archive file
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build V8 and J2V8 for Android
      run: |
        python2 build.py -t android -a x86 --docker --keep-native-libs v8 j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java
        python2 build.py -t android -a arm --docker --keep-native-libs v8 j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java
        python2 build.py -t android -a x86_64 --docker --keep-native-libs v8 j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java
        python2 build.py -t android -a arm64 --docker --keep-native-libs v8 j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java

    - name: Archive J2V8 Android aar file
      uses: actions/upload-artifact@v1.0.0
      with:
        name: j2v8-android-aar
        path: build/outputs/aar/j2v8-release.aar
